### ISSUE TITLE
How to using ssl-root-cas with TCP socket?

### ISSUE THREAD

**Issue by lygstate** [Daplie/node-ssl-root-cas#29]
Not https, but TCP with ssl support.

**Comment by coolaj86** [comment]
The `ca` option of [tls.createSecureContext(options)](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options).

I also added an example of this to the README.

**Comment by lygstate** [comment]
ca？ would it automatically detecting root certificate？

**Comment by coolaj86** [comment]
Certificate authority is a chain. The root certificates bundled by mozilla (and distributed with openssl and node.js) are used by default and any additional can be specified manually to the `ca` option as referenced in the documentation.

Whenever a server (or client) presents a certificate (which must include any intermediates), it's checked against each root in the chain.

**Comment by lygstate** [comment]
Then that's weird cause my site are already with certification

**Comment by coolaj86** [comment]
I'm not sure what it is you're trying to accomplish, but I don't think you need to use this module.
