### ISSUE TITLE
Please deprecate this package in favor of NODE_EXTRA_CA_CERTS on node@^7.3.0

### ISSUE THREAD

**Issue by JLHwung** [Daplie/node-ssl-root-cas#31]
Node.js have built-in NODE_EXTRA_CA_CERTS environment variables doing the same thing as this package, see https://github.com/nodejs/node/pull/9139

Please consider deprecate this package on node@^7.3.0

**Comment by coolaj86** [comment]
There are other uses for the package as well, but I will note in the README that people *probably* should use `NODE_EXTRA_CA_CERTS`.

**Comment by coolaj86** [comment]
I've updated the README and, as also noted by @sam-github, see this as a tool in the toolbox with potential other uses, and not a need to formally deprecate this package.
