### ISSUE TITLE
minor inaccuracy in the docs about "bundled" .ca certs

### ISSUE THREAD

**Issue by sam-github** [Daplie/node-ssl-root-cas#32]
> You must use a bundled certificate for your server (the server and intermediates, not root), but you cannot use bundles ca property.

The .ca property can contain concatenated PEM certificates, and they are all added. Btw, I wouldn't use the word "bundle" for this, its not clear what it means, though I am pretty sure you mean concatenated PEM files.

Did you find this not to be true on some node version? If so, I could backport the feature.

**Comment by coolaj86** [comment]
Yes by "bundle" I mean "concatenate".

And that sentence is poorly constructed. What I meant to say is that the `cert` property is for what you send to the clients (which you must use) whereas the `ca` property is for peer-certificate checking (which would be the wrong thing to do).

**Comment by sam-github** [comment]
Though you can add your own cert chain to `.ca` - I think its weird, but it works: https://github.com/nodejs/node/pull/10389/commits/64c81438c634c05fef97ccd76855cb85689846ef
