### ISSUE TITLE
Clean up 'pems' directory

### ISSUE THREAD

**Issue by gregmac** [Daplie/node-ssl-root-cas#5]
I think there are many issues with the 'pems' directory implementation, but I don't know how to solve them because I don't know what the purpose is.

First off: What _is_ the purpose of having the pems directory?

---

Issues:
- The names of the files in the pems directory are meaningless and unpredictable; they are entirely dependent on the ordering mozilla.org uses. 
- The pems directory is overwritten during npm install with the latest packages from mozilla.org, making it somewhat pointless to have included in the package and source control in the first place
- If there are fewer CAs on mozilla.org than in the package, the 'extras' in the package are left untouched. Eg: if at time of packaging, there are 140 CAs, but at the time the user installs (much later) there are only 138 CAs, then _for that user_ `pems/ca-139.pem` and `pems/ca-140.pem` will either be duplicates or invalid certificates, with no indication of any problem

I will refrain from further discussion until understanding the purpose.

If there is no purpose, then everything related to this 'pems' directory should just be removed.

**Comment by coolaj86** [comment]
Well, after all these years the need to clean this up hasn't arisen so I'm going to just close the issue.

However, https://github.com/Daplie/node-ssl-root-cas/pull/33 may address this in some ways.
